// test_pseudo_claims_onramp.js — the pseudo-claims first-run on-ramp (issue onramp-ux)
// Copyright (c) 2026 Andrew Schulman
// https://github.com/aschulman42-cell/code-exam
// Co-authored with Claude (Claude Code).
// Licensed under the Apache License, Version 2.0; see LICENSE.
/**
 * test_pseudo_claims_onramp.js — the pseudo-claims on-ramp messaging.
 *
 * A naive first-run of --pseudo-claims should guide the user, and must never
 * assert language-model output that did not happen:
 *   - bare `--pseudo-claims` errors AND shows the candidates recipe;
 *   - a model-less `--pseudo-claims @anchors` announces it is showing EVIDENCE
 *     PACKS only (no claims), and does NOT print the "generated by a language
 *     model" framing (no model ran).
 *
 * Run: node --test test/test_pseudo_claims_onramp.js
 */

import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'fs';
import path from 'path';
import os from 'os';
import { execSync } from 'child_process';

const TEST_DIR = path.join(os.tmpdir(), 'ce_test_pc_onramp');
const CLI = path.resolve('src/index.js');
const SRC_DIR = path.join(TEST_DIR, 'src');
const IDX_DIR = path.join(TEST_DIR, '.idx');
const ANCHORS = path.join(TEST_DIR, 'anchors.lst');

function runCLI(args) {
  try {
    return execSync(`node ${CLI} ${args}`, { encoding: 'utf-8', timeout: 30000, cwd: TEST_DIR });
  } catch (e) {
    return (e.stdout || '') + (e.stderr || '');
  }
}

before(() => {
  fs.mkdirSync(SRC_DIR, { recursive: true });
  let body = 'def main():\n    helper()\n    worker()\n\n';
  body += 'def helper():\n    x = 1\n    return x + 1\n\n';
  body += 'def worker():\n    y = 2\n    return y + 2\n\n';
  fs.writeFileSync(path.join(SRC_DIR, 'app.py'), body);
  runCLI(`--build-index ${SRC_DIR} --index-path ${IDX_DIR} --skip-semantic 2>&1`);
  // A valid, resolvable anchor for the pack-only run.
  fs.writeFileSync(ANCHORS, '# Sample mechanism\napp.py@main\n');
});

after(() => {
  fs.rmSync(TEST_DIR, { recursive: true, force: true });
});

describe('pseudo-claims bare-error on-ramp', () => {
  it('bare --pseudo-claims errors and shows the --candidates recipe', () => {
    const out = runCLI(`--pseudo-claims --index-path ${IDX_DIR} 2>&1`);
    assert.match(out, /no anchors given/i, 'should still say no anchors given: ' + out);
    assert.match(out, /--candidates/, 'should point at the candidates on-ramp: ' + out);
    assert.match(out, /anchors\.lst/i, 'should name an anchors list in the recipe: ' + out);
  });
});

describe('pseudo-claims model-less pack-only run', () => {
  it('shows an evidence-packs-only banner and no claims', () => {
    const out = runCLI(`--pseudo-claims @${ANCHORS} --index-path ${IDX_DIR} 2>&1`);
    assert.match(out, /evidence pack/i, 'should announce evidence packs: ' + out);
    assert.match(out, /no claims|No model/i, 'should say no claims were drafted / no model: ' + out);
  });

  it('does NOT claim the output was generated by a language model', () => {
    const out = runCLI(`--pseudo-claims @${ANCHORS} --index-path ${IDX_DIR} 2>&1`);
    assert.doesNotMatch(out, /generated by a language model/i,
      'no model ran — must not frame the packs as LLM output: ' + out);
  });
});
