// pseudo-claims.js — `--pseudo-claims`: draft illustrative patent-style
// "pseudo-claims" from evidence packs of explicit anchor functions.
//
// v1 is EXPLICIT-ANCHOR ONLY: the user supplies "file@func" anchors; CE does
// NOT auto-discover them. Auto-discovery ("point it at a codebase") is deferred
// and gated on #280 (connected multi-scope matching) — see issue #281. The
// distractor test showed a noisy pack makes a model draft confident, coherent
// claims about the WRONG functions (precision ~29%), so v1 stays anchor-driven.
//
// One anchor GROUP == one pseudo-claim: the functions in a group are the ones
// that jointly embody a single mechanism. The inline form "a@f;b@g" is one
// group; an @anchors.lst file may hold several groups, a "# Label" line starting
// a new one — so a multi-claim document maps to one file, one claim per group.
//
// This module is the DETERMINISTIC scaffold (#281 scaffold item): it parses
// anchors into groups, resolves + extracts each one (a real function-existence
// check), assembles a bounded evidence pack per group, and emits the
// non-removable PSEUDO / non-admission caveat. The LLM draft step is added by
// the companion item (issue-281-pseudo-claims-generate); until then
// `--pseudo-claims` runs the pack-only path and says so.

import fs from 'node:fs';
import { parseFuncSpec } from '../utils.js';

// --- Canonical caveat blocks -------------------------------------------------
// Ported verbatim from pseudo_claim_selftest/CAVEAT.md so the shipped command
// carries them as SOURCE. The tool emits these unconditionally and first — they
// are never left to the model (which could soften or omit a "please add a
// disclaimer" instruction). Block A prefixes the whole artifact; Block B labels
// each individual claim so a claim lifted out of context still carries the
// non-admission framing; Block C is the compact one-line footer.
export const PSEUDO_CLAIM_CAVEAT_A = [
  '# PSEUDO-CLAIMS — illustrative drafting exercise, NOT legal analysis',
  '',
  'The material below consists of **pseudo patent claims**: hypothetical,',
  'illustrative claim-style descriptions generated by a language model as a',
  '**drafting and code-navigation exercise**. It is **not** legal advice, **not**',
  'a patent-attorney work product, **not** a prior-art search, and **not** an',
  'opinion on novelty, non-obviousness, validity, or infringement.',
  '',
  '**These pseudo-claims are not admissions or statements of fact.** Nothing here',
  'asserts, and nothing here should be read as asserting, that the examined',
  'codebase — or any other codebase, product, or party — actually embodies,',
  'practices, implements, or infringes any claim or claim element. Any',
  '`file:line` reference is an **orientation pointer** to code that is',
  '*topically related* to the drafted language — a navigation aid for a human',
  'reviewer — **not** a determination that the cited code implements the claim.',
  '',
  'Machine-generated and unreviewed. Do not rely on it for any legal purpose.',
  'Consult qualified patent counsel before drawing any conclusion.',
].join('\n');

export const PSEUDO_CLAIM_CAVEAT_B =
  '**[PSEUDO-CLAIM — illustrative only; not a legal opinion or admission that any ' +
  'code practices this. `file:line` = orientation pointer, not a finding.]**';

export const PSEUDO_CLAIM_CAVEAT_C =
  "_Pseudo-claims: illustrative LLM drafting, not legal advice, not admissions; " +
  "pointers orient, they don't assert implementation._";

// Evidence-pack size bounds (per group, shared with the generate item so the
// pack the user eyeballs in dry-run matches what the model would receive).
export const PACK_PER_ANCHOR_CHARS = 8000;
export const PACK_TOTAL_CHARS = 24000;

// A fence longer than the longest backtick run in `body` — CE's own source is
// full of backtick template literals, so a fixed ``` fence would break out of
// the block mid-body.
function fenceFor(body) {
  const longest = (String(body).match(/`+/g) || []).reduce((n, s) => Math.max(n, s.length), 0);
  return '`'.repeat(Math.max(3, longest + 1));
}

// Partition the command value into anchor GROUPS (one group == one pseudo-claim).
//   - inline "a@f;b@g"  -> a single group (label null)
//   - "@anchors.lst"    -> one-or-more groups; a "# Label" line starts a new
//                          group and names it; anchors before any header form an
//                          implicit first group; blank lines ignored.
function collectAnchorGroups(spec) {
  if (!spec || !spec.startsWith('@')) {
    const specs = String(spec || '').split(';').map((s) => s.trim()).filter(Boolean);
    return specs.length ? [{ label: null, specs }] : [];
  }
  const listPath = spec.slice(1);
  const text = fs.readFileSync(listPath, 'utf8'); // caller catches ENOENT
  const groups = [];
  let cur = null;
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line) continue;
    if (line.startsWith('#')) {
      const label = line.replace(/^#+/, '').trim();
      cur = { label: label || null, specs: [] };
      groups.push(cur);
      continue;
    }
    if (!cur) { cur = { label: null, specs: [] }; groups.push(cur); }
    cur.specs.push(line);
  }
  return groups.filter((g) => g.specs.length);
}

// Resolve one group's anchor specs to real functions (the existence check the
// file-level prototype lacked — it cited fragments like strRe.exec(body)).
function resolveGroup(index, group) {
  const resolved = [];
  const problems = [];
  for (const a of group.specs) {
    const { fileHint, funcName } = parseFuncSpec(a);
    const matches = index.findFunctionMatches(funcName, fileHint);
    if (!matches || matches.length === 0) {
      problems.push({ spec: a, reason: 'no function in the index resolves to this anchor' });
      continue;
    }
    if (matches.length > 1) {
      const opts = matches.slice(0, 5).map((m) => `${m.filepath}@${m.name} (L${m.start}-${m.end})`).join('; ');
      const more = matches.length > 5 ? `; …+${matches.length - 5} more` : '';
      problems.push({ spec: a, reason: `ambiguous — ${matches.length} functions match; use an exact file@func (e.g. ${opts}${more})` });
      continue;
    }
    const m = matches[0];
    const source = index.getFunctionSource(m.filepath, m.name);
    if (!source) {
      problems.push({ spec: a, reason: 'matched, but source could not be extracted (file content not loaded in this index)' });
      continue;
    }
    resolved.push({ spec: a, filepath: m.filepath, name: m.name, start: m.start, end: m.end, source });
  }
  return { resolved, problems };
}

// Assemble a bounded evidence pack from a group's resolved anchors.
function buildPack(resolved) {
  const packParts = [];
  let used = 0;
  let droppedForBudget = 0;
  const truncatedAnchors = [];
  for (const r of resolved) {
    if (used >= PACK_TOTAL_CHARS) { droppedForBudget++; continue; }
    let body = r.source;
    if (body.length > PACK_PER_ANCHOR_CHARS) {
      body = body.slice(0, PACK_PER_ANCHOR_CHARS) + '\n// … [truncated for evidence-pack budget]';
      truncatedAnchors.push(r.spec);
    }
    const header = `${r.filepath}@${r.name}  (L${r.start}-${r.end})`;
    const fence = fenceFor(body);
    packParts.push(`// ${header}\n${fence}\n${body}\n${fence}`);
    used += body.length;
  }
  return { pack: packParts.join('\n\n'), truncatedAnchors, droppedForBudget };
}

/**
 * Handle `--pseudo-claims <anchors>` (scaffold: deterministic, pack-only).
 * Partitions anchors into groups (one pseudo-claim each), resolves + extracts
 * each, assembles a bounded evidence pack per group, and emits the caveat +
 * per-claim anchor table + pack. Sets process.exitCode on error.
 */
export async function doPseudoClaims(index, args) {
  const spec = args.pseudo_claims;

  let groups;
  try {
    groups = collectAnchorGroups(spec);
  } catch (e) {
    console.error(`--pseudo-claims: could not read anchor list '${String(spec).slice(1)}': ${e.message}`);
    process.exitCode = 1;
    return;
  }
  if (groups.length === 0) {
    console.error('--pseudo-claims: no anchors given. Provide "file@func;file@func" or @anchors.lst (one file@func per line; "# Label" lines separate claims).');
    process.exitCode = 1;
    return;
  }

  const multi = groups.length > 1;

  // Resolve + pack each group.
  const sections = [];
  let totalResolved = 0;
  let totalProblems = 0;
  groups.forEach((g, gi) => {
    const { resolved, problems } = resolveGroup(index, g);
    const { pack, truncatedAnchors, droppedForBudget } = buildPack(resolved);
    sections.push({ label: g.label, groupNum: gi + 1, resolved, problems, pack, truncatedAnchors, droppedForBudget });
    totalResolved += resolved.length;
    totalProblems += problems.length;
  });

  // Report dropped anchors to stderr (grouped when there are multiple claims),
  // so stdout stays a clean artifact.
  if (totalProblems) {
    console.error(`\n${totalProblems} anchor(s) dropped (did not resolve to a real function):`);
    for (const s of sections) {
      if (!s.problems.length) continue;
      if (multi) console.error(`  [${s.label || `group ${s.groupNum}`}]`);
      for (const p of s.problems) console.error(`  ✗ ${p.spec} — ${p.reason}`);
    }
    console.error('');
  }
  if (totalResolved === 0) {
    console.error('--pseudo-claims: no anchors resolved to real functions; nothing to draft.');
    process.exitCode = 1;
    return;
  }

  // Build the artifact: Block A once, then one section per non-empty group.
  const withAnchors = sections.filter((s) => s.resolved.length);
  const out = [];
  out.push(PSEUDO_CLAIM_CAVEAT_A);
  out.push('');
  out.push(`_Deterministic scaffold: below is the exact, size-capped evidence pack a model would be handed — one per pseudo-claim (${withAnchors.length}). LLM drafting lands in \`issue-281-pseudo-claims-generate\`._`);
  out.push('');
  withAnchors.forEach((s, i) => {
    const label = s.label ? ` — ${s.label}` : '';
    out.push(`## Pseudo-claim ${i + 1}${label}`);
    out.push('');
    out.push(`### Anchors (${s.resolved.length})`);
    out.push('');
    for (const a of s.resolved) {
      out.push(`- \`${a.filepath}@${a.name}\` — L${a.start}-${a.end} (${a.end - a.start + 1} lines)`);
    }
    out.push('');
    out.push('### Evidence pack');
    out.push('');
    if (s.truncatedAnchors.length) {
      out.push(`_Truncated to the ${PACK_PER_ANCHOR_CHARS}-char per-anchor cap: ${s.truncatedAnchors.map((x) => `\`${x}\``).join(', ')}._`);
      out.push('');
    }
    if (s.droppedForBudget) {
      out.push(`_${s.droppedForBudget} anchor(s) omitted after the ${PACK_TOTAL_CHARS}-char per-claim pack budget was reached._`);
      out.push('');
    }
    out.push(s.pack);
    out.push('');
  });
  out.push(PSEUDO_CLAIM_CAVEAT_C);

  const text = out.join('\n') + '\n';

  // Emit to stdout or --pseudo-out <file>.
  if (args.pseudo_out) {
    try {
      fs.writeFileSync(args.pseudo_out, text, 'utf8');
      console.log(`Wrote pseudo-claims artifact to ${args.pseudo_out} — ${withAnchors.length} pseudo-claim(s), ${totalResolved} anchor(s)${totalProblems ? `, ${totalProblems} dropped` : ''}.`);
    } catch (e) {
      console.error(`--pseudo-claims: could not write '${args.pseudo_out}': ${e.message}`);
      process.exitCode = 1;
    }
  } else {
    process.stdout.write(text);
  }
}
