// pseudo-claims.js — `--pseudo-claims`: draft illustrative patent-style
// "pseudo-claims" from evidence packs of explicit anchor functions.
//
// v1 is EXPLICIT-ANCHOR ONLY: the user supplies "file@func" anchors; CE does
// NOT auto-discover them. Auto-discovery ("point it at a codebase") is deferred
// and gated on #280 (connected multi-scope matching) — see issue #281. The
// distractor test showed a noisy pack makes a model draft confident, coherent
// claims about the WRONG functions (precision ~29%), so v1 stays anchor-driven.
//
// One anchor GROUP == one pseudo-claim: the functions in a group are the ones
// that jointly embody a single mechanism. The inline form "a@f;b@g" is one
// group; an @anchors.lst file may hold several groups, a "# Label" line starting
// a new one — so a multi-claim document maps to one file, one claim per group.
//
// Pipeline (all deterministic except the one LLM draft):
//   1. Parse anchors into groups; resolve + extract each (function-existence
//      check); assemble a bounded evidence pack per group.
//   2. Draft one CLAIM paragraph + element->file@func map per pack, via a local
//      GGUF (--model, GPU->CPU fallback) or an OpenAI-compatible endpoint
//      (CE_OPENAI_API_URL), honoring the air-gap. --dry-run (or no model) stops
//      after step 1 and prints the packs.
//   3. Grounding pass: every cited anchor must resolve to a real function or it
//      is dropped (a separate anti-fabrication control from the caveat).
//   4. Emit the non-removable PSEUDO / non-admission caveat (tool-emitted, never
//      the model), a per-claim Block-B label, the drafted claim, its grounded
//      anchor map, and the evidence pack it was grounded in.

import fs from 'node:fs';
import { parseFuncSpec } from '../utils.js';
import { resolveModel, makeDrafter, claimsCostGate, actualCostLine, resetCloudUsage } from '../core/llm-runner.js';
import { rankCandidates, buildBatchPrompt } from '../core/mechanism-ranker.js';
import { groupMechanisms, formatAnchors, scoreGrouping, parseAnchorHeader, docAnchorsForGroup, GROUPER_DEFAULTS } from '../core/mechanism-grouper.js';

// --- Canonical caveat blocks -------------------------------------------------
// Ported verbatim from pseudo_claim_selftest/CAVEAT.md so the shipped command
// carries them as SOURCE. The tool emits these unconditionally and first — they
// are never left to the model (which could soften or omit a "please add a
// disclaimer" instruction). Block A prefixes the whole artifact; Block B labels
// each individual claim so a claim lifted out of context still carries the
// non-admission framing; Block C is the compact one-line footer.
export const PSEUDO_CLAIM_CAVEAT_A = [
  '# PSEUDO-CLAIMS — illustrative drafting exercise, NOT legal analysis',
  '',
  'The material below consists of **pseudo patent claims**: hypothetical,',
  'illustrative claim-style descriptions generated by a language model as a',
  '**drafting and code-navigation exercise**. It is **not** legal advice, **not**',
  'a patent-attorney work product, **not** a prior-art search, and **not** an',
  'opinion on novelty, non-obviousness, validity, or infringement.',
  '',
  '**These pseudo-claims are not admissions or statements of fact.** Nothing here',
  'asserts, and nothing here should be read as asserting, that the examined',
  'codebase — or any other codebase, product, or party — actually embodies,',
  'practices, implements, or infringes any claim or claim element. Any',
  '`file:line` reference is an **orientation pointer** to code that is',
  '*topically related* to the drafted language — a navigation aid for a human',
  'reviewer — **not** a determination that the cited code implements the claim.',
  '',
  'Machine-generated and unreviewed. Do not rely on it for any legal purpose.',
  'Consult qualified patent counsel before drawing any conclusion.',
].join('\n');

export const PSEUDO_CLAIM_CAVEAT_B =
  '**[PSEUDO-CLAIM — illustrative only; not a legal opinion or admission that any ' +
  'code practices this. `file:line` = orientation pointer, not a finding.]**';

export const PSEUDO_CLAIM_CAVEAT_C =
  "_Pseudo-claims: illustrative LLM drafting, not legal advice, not admissions; " +
  "pointers orient, they don't assert implementation._";

// The model's drafting instruction — ported from pseudo_claim_selftest's
// GENERATE_SYS (validated on Qwen2.5-14B/32B). The strict CLAIM:/ANCHORS: format
// is what parseGeneratedClaim() below relies on, and the "cite ONLY files and
// functions that appear in the provided code" rule is reinforced by the
// deterministic grounding pass (a model instruction alone is not trusted).
export const PSEUDO_CLAIM_GENERATE_SYS =
  'You draft ONE hypothetical, illustrative PSEUDO patent claim for a software ' +
  'mechanism, as a drafting exercise only (not legal advice, not an admission). ' +
  'You are given source code, and may be given a MECHANISM line naming the ' +
  'intended subject and purpose. If a MECHANISM line is present, draft the claim ' +
  'for THAT mechanism — treat it as the intended subject and purpose; do not ' +
  'substitute a different purpose inferred from the code. Output EXACTLY this ' +
  'format and nothing else:\n' +
  'CLAIM: <one self-contained paragraph in standard method/apparatus form: a ' +
  'preamble ending in a colon, then each element/step as a SEMICOLON-delimited ' +
  'clause — e.g. "A method for X, comprising: <step>; <step>; and <step>.">\n' +
  'ANCHORS:\n' +
  '- <file>@<functionName> — <the claim element it implements>\n' +
  '(one line per distinct element). For a DOCUMENTATION excerpt shown in the ' +
  'provided material, cite it as <file>@L<start>-<end> using the line range ' +
  'from its header. Cite ONLY files, functions, and line ranges that appear ' +
  'in the provided material. NEVER invent a path, a name, or a line range.';

// Evidence-pack size bounds (per group, shared so the pack the user eyeballs in
// dry-run is exactly what the model receives).
export const PACK_PER_ANCHOR_CHARS = 8000;
export const PACK_TOTAL_CHARS = 24000;

// A fence longer than the longest backtick run in `body` — CE's own source is
// full of backtick template literals, so a fixed ``` fence would break out of
// the block mid-body.
function fenceFor(body) {
  const longest = (String(body).match(/`+/g) || []).reduce((n, s) => Math.max(n, s.length), 0);
  return '`'.repeat(Math.max(3, longest + 1));
}

// Partition the command value into anchor GROUPS (one group == one pseudo-claim).
//   - inline "a@f;b@g"  -> a single group (label null)
//   - "@anchors.lst"    -> one-or-more groups; a "# Label" line starts a new
//                          group and names it; anchors before any header form an
//                          implicit first group; blank lines ignored.
// Headers are parsed via parseAnchorHeader (the grouper emit's inverse), so a
// group carries a CLEAN {label, priority, purpose} — the `(N fns)` count,
// `[P…]` priority tag, and ranker note are stripped rather than riding into
// the MECHANISM hint and the output heading. The hint itself is KEPT (label +
// purpose); only the triage annotations are removed. Priority never reaches
// the drafter — its one consumer is the --min-rank draft filter. Exported for
// tests.
export function collectAnchorGroups(spec) {
  if (!spec || !spec.startsWith('@')) {
    const specs = String(spec || '').split(';').map((s) => s.trim()).filter(Boolean);
    return specs.length ? [{ label: null, priority: null, fold: null, purpose: '', specs }] : [];
  }
  const listPath = spec.slice(1);
  const text = fs.readFileSync(listPath, 'utf8'); // caller catches ENOENT
  const groups = [];
  let cur = null;
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line) continue;
    if (line.startsWith('#')) {
      const { label, priority, fold, purpose } = parseAnchorHeader(line);
      cur = { label: label || null, priority: priority ?? null, fold: fold ?? null, purpose: purpose || '', specs: [] };
      groups.push(cur);
      continue;
    }
    if (!cur) { cur = { label: null, priority: null, fold: null, purpose: '', specs: [] }; groups.push(cur); }
    cur.specs.push(line);
  }
  return groups.filter((g) => g.specs.length);
}

// #291 Part B: pack-budget omissions must be visible in the LEAN artifact too
// (the --min-rank disclosure principle applied to evidence packs) — a claim
// drafted from 8 of a group's 121 anchors silently presenting itself as the
// whole group is how Bram pseudo-claim 1 happened. Exported for tests.
export function packDisclosure(s) {
  const dropped = s.droppedForBudget || 0;
  const truncated = (s.truncatedAnchors || []).length;
  if (!dropped && !truncated) return '';
  const total = (s.resolved || []).length;
  const bits = [`packed ${total - dropped} of ${total} resolved anchor(s)`];
  if (dropped) bits.push(`${dropped} omitted for the pack budget`);
  if (truncated) bits.push(`${truncated} truncated`);
  return `_Evidence pack: ${bits.join('; ')}._`;
}

// issue-286-doc-line-anchors: `path@L<start>[-<end>]` is a LINE-RANGE anchor,
// valid on ANY indexed file — which is what lets DOCUMENTATION be cited as
// evidence (patent practice cites manuals and printed publications alongside
// code; CE's --use-docs experiment (de47d0b) established the term-vote channel
// is the wrong way to use docs while this evidence channel was unbuilt).
// Parsed HERE, not in the shared parseFuncSpec — the draft pipeline is the
// only consumer; #286's cross-command @line normalization stays open.
// Exported for tests.
export function parseLineAnchor(spec) {
  const m = String(spec || '').trim().match(/^(.+)@L(\d+)(?:-(\d+))?$/);
  if (!m) return null;
  const start = Number(m[2]);
  const end = m[3] ? Number(m[3]) : start;
  if (start < 1 || end < start) return null;
  return { file: m[1].trim(), start, end };
}

// Resolve a (possibly suffix-abbreviated) path against the index's fileLines:
// exact key first, else a UNIQUE suffix match (slash-normalized). Returns the
// indexed key, null on miss, or { ambiguous: true } — a doc cite must resolve
// to exactly one indexed file, same anti-fabrication posture as functions.
function resolveIndexedFile(index, p) {
  const fl = index.fileLines;
  if (!fl || typeof fl.get !== 'function') return null;
  if (fl.has(p)) return p;
  const norm = String(p).replace(/\\/g, '/');
  let hit = null, count = 0;
  for (const key of fl.keys()) {
    const k = String(key).replace(/\\/g, '/');
    if (k === norm || k.endsWith('/' + norm)) { hit = key; count++; if (count > 1) return { ambiguous: true }; }
  }
  return count === 1 ? hit : null;
}

// Resolve one group's anchor specs to real functions (the existence check the
// file-level prototype lacked — it cited fragments like strRe.exec(body)) —
// or, for `path@L<start>-<end>` specs, to line-range excerpts of any indexed
// file (issue-286-doc-line-anchors).
function resolveGroup(index, group) {
  const resolved = [];
  const problems = [];
  for (const a of group.specs) {
    const la = parseLineAnchor(a);
    if (la) {
      const hit = resolveIndexedFile(index, la.file);
      if (!hit || hit.ambiguous) {
        problems.push({ spec: a, reason: hit && hit.ambiguous ? 'line-anchor path is ambiguous in the index — use a longer suffix' : 'line-anchor file is not in the index' });
        continue;
      }
      const lines = index.fileLines.get(hit) || [];
      if (la.start > lines.length) {
        problems.push({ spec: a, reason: `line range starts past end of file (${lines.length} lines)` });
        continue;
      }
      const end = Math.min(la.end, lines.length);
      const source = lines.slice(la.start - 1, end).join('\n');
      if (!source.trim()) { problems.push({ spec: a, reason: 'line range is empty' }); continue; }
      resolved.push({ spec: a, filepath: hit, name: `L${la.start}-${end}`, start: la.start, end, source, kind: 'lines' });
      continue;
    }
    const { fileHint, funcName } = parseFuncSpec(a);
    const matches = index.findFunctionMatches(funcName, fileHint);
    if (!matches || matches.length === 0) {
      problems.push({ spec: a, reason: 'no function in the index resolves to this anchor' });
      continue;
    }
    if (matches.length > 1) {
      const opts = matches.slice(0, 5).map((m) => `${m.filepath}@${m.name} (L${m.start}-${m.end})`).join('; ');
      const more = matches.length > 5 ? `; …+${matches.length - 5} more` : '';
      problems.push({ spec: a, reason: `ambiguous — ${matches.length} functions match; use an exact file@func (e.g. ${opts}${more})` });
      continue;
    }
    const m = matches[0];
    const source = index.getFunctionSource(m.filepath, m.name);
    if (!source) {
      problems.push({ spec: a, reason: 'matched, but source could not be extracted (file content not loaded in this index)' });
      continue;
    }
    resolved.push({ spec: a, filepath: m.filepath, name: m.name, start: m.start, end: m.end, source });
  }
  return { resolved, problems };
}

// Path A (pseudo-claims-purpose-harvest): mechanically harvest a group's PURPOSE
// from its comments, index-native, via the same digest builder `--comments-only`
// uses. Class group -> the class's comments; token group -> the namesake-token
// file's comments (else the group's key function). Written into the candidate
// `.lst` header at `--candidates` emit time so it is visible/prunable and travels
// with the group into drafting (where the label becomes the MECHANISM: hint).
const HARVEST_CAP = 700;
function harvestPurpose(index, label, members) {
  const commentsOf = (target) => {
    try {
      const d = index.buildDigest(target, { maxCallers: 0, maxCallees: 0, maxStrings: 0 });
      if (d && d.comments && d.comments.length) return [...d.comments].sort((a, b) => a.line - b.line);
    } catch (_) { /* target didn't resolve */ }
    return [];
  };
  const join = (cs) => cs.map((c) => c.text).join(' ').replace(/\s+/g, ' ').trim();
  // A file's LEADING comment block = its purpose header (catches // banners too).
  // Empty when nothing sits near the top (big multi-purpose files) -> caller falls back.
  const fileHeader = (file) => {
    const cs = commentsOf(file);
    if (!cs.length || cs[0].line > 8) return '';
    return join(cs.filter((c) => c.line <= 30));
  };
  const files = [...new Set((members || []).map((m) => m.file).filter(Boolean))];
  const primaryFile = (tok) => {
    if (tok) { const hit = files.find((f) => f.replace(/^.*\//, '').toLowerCase().includes(tok.toLowerCase())); if (hit) return hit; }
    return files.slice().sort((a, b) => members.filter((m) => m.file === b).length - members.filter((m) => m.file === a).length)[0] || null;
  };
  let purpose = '';
  const classM = (label || '').match(/^\[class\]\s+(\S+)/);
  if (classM) {
    const f = primaryFile(null);                        // the class's file -> its header
    purpose = (f && fileHeader(f)) || join(commentsOf(classM[1])); // else class-scope comments
  } else {
    const tokenM = (label || '').match(/^(\S+)\s*\(([^)]+)\)/);    // "token (namesakeFn) …"
    const token = tokenM ? tokenM[1] : '';
    const namesake = tokenM ? tokenM[2] : '';
    const f = primaryFile(token);                       // namesake-token file -> its header
    purpose = (f && fileHeader(f)) || (namesake ? join(commentsOf(namesake)) : '');
  }
  if (!purpose && members && members.length) purpose = join(commentsOf(members[0].bare || members[0].name));
  return purpose ? purpose.slice(0, HARVEST_CAP) : '';
}

// --min-rank (pseudo-claims-min-rank): user-controlled draft-time floor over
// the [P..] tags parseAnchorHeader surfaces. Selection happens at CONSUMPTION
// so the ranked .lst stays a complete, auditable artifact. Default is P2 —
// but only when the list actually carries rank tags (an unranked list drafts
// everything; no silent surprise). Untagged/[unscored] groups always draft
// (can't judge -> don't silently drop). The ranker's tags remain observe-only
// annotations under their caveat block; the filter is the USER'S explicit
// instruction (or an overridable default), which keeps CE out of worthiness
// opinions. Exported for tests.
export function parseMinRank(v) {
  if (v == null || v === '') return null;
  const m = String(v).trim().match(/^[pP]?([0-3])$/);
  return m ? Number(m[1]) : NaN;
}

export function filterGroupsByMinRank(groups, minRankValue) {
  const floor = parseMinRank(minRankValue);
  const tagged = groups.some((g) => g.priority != null);
  const effective = floor != null ? floor : (tagged ? 2 : null);
  if (effective == null || effective === 0) return { groups, floor: effective, dropped: 0, tagged };
  const kept = groups.filter((g) => g.priority == null || g.priority >= effective);
  return { groups: kept, floor: effective, dropped: groups.length - kept.length, tagged };
}

// chart-toc-rank-display: the claim's own PREAMBLE clause (text up to the
// first ':') is its best human-readable name — grouper labels like
// `[file] json-stream.js` say where a claim came from, not what it is about.
// Exported for tests.
export function claimPreambleSnippet(prose, max = 90) {
  const text = String(prose || '').trim();
  if (!text) return '';
  const ci = text.indexOf(':');
  let pre = (ci > 0 ? text.slice(0, ci) : text).replace(/\s+/g, ' ').trim();
  if (pre.length > max) pre = pre.slice(0, max - 1).trimEnd() + '…';
  return pre;
}

// chart-toc-rank-display: table-of-contents lines for a multi-claim chart —
// rank + grouper label + preamble snippet. Tool-emitted AFTER drafting, so
// (like the heading rank suffix) nothing here ever reaches the model and the
// MECHANISM hint stays clean. Exported for tests.
export function formatChartToc(rows) {
  const out = ['## Contents', ''];
  for (const r of rows) {
    const rank = r.priority != null ? `[P${r.priority}] ` : '';
    out.push(`${r.n}. ${rank}${r.label || '(unlabeled)'}${r.preamble ? ` — "${r.preamble}"` : ''}`);
  }
  out.push('');
  return out;
}

// Assemble a bounded evidence pack from a group's resolved anchors.
function buildPack(resolved) {
  const packParts = [];
  let used = 0;
  let droppedForBudget = 0;
  const truncatedAnchors = [];
  for (const r of resolved) {
    if (used >= PACK_TOTAL_CHARS) { droppedForBudget++; continue; }
    let body = r.source;
    if (body.length > PACK_PER_ANCHOR_CHARS) {
      body = body.slice(0, PACK_PER_ANCHOR_CHARS) + '\n// … [truncated for evidence-pack budget]';
      truncatedAnchors.push(r.spec);
    }
    const header = r.kind === 'lines'
      ? `${r.filepath}@L${r.start}-${r.end}  (documentation excerpt)`
      : `${r.filepath}@${r.name}  (L${r.start}-${r.end})`;
    const fence = fenceFor(body);
    packParts.push(`// ${header}\n${fence}\n${body}\n${fence}`);
    used += body.length;
  }
  return { pack: packParts.join('\n\n'), truncatedAnchors, droppedForBudget };
}

// --- Model drafting (the one non-deterministic step) -------------------------

// Parse the model's "CLAIM: … ANCHORS: - file@func — element" reply into
// { prose, anchors:[{file,func,line,element}] }. Ported from the prototype's
// parseGeneratedClaim. Tolerant of leading bullets, em/en/double-dash element
// separators, and a `()` suffix on function names.
export function parseGeneratedClaim(text) {
  const t = String(text || '');
  const claimM = t.match(/CLAIM:\s*([\s\S]*?)(?:\n\s*ANCHORS:|$)/i);
  const prose = (claimM ? claimM[1] : t.split(/ANCHORS:/i)[0]).trim().replace(/\s+/g, ' ');
  const anchorsBlock = t.split(/ANCHORS:/i)[1] || '';
  const anchors = [];
  for (const ln of anchorsBlock.split(/\r?\n/)) {
    const m = ln.match(/^[\s\-*]+(.+)$/);
    if (!m) continue;
    const parts = m[1].trim().split(/\s[—–-]\s|\s--\s/);
    const ref = (parts[0] || '').trim().replace(/[`'"]/g, '');
    const element = (parts.slice(1).join(' ') || '').trim();
    let file = ref, func = '', line = 0;
    const at = ref.split('@');
    if (at.length === 2) { file = at[0].trim(); func = at[1].trim().replace(/\(\)$/, ''); }
    else { const col = ref.match(/^(.+):(\d+)/); if (col) { file = col[1].trim(); line = Number(col[2]); } }
    if (file) anchors.push({ file, func, line, element });
  }
  return { prose, anchors };
}

// Grounding pass: keep only cited anchors whose function resolves to a real
// function in the index (a SEPARATE anti-fabrication control from the caveat —
// the caveat governs how cited code is characterized; grounding governs whether
// the citation exists). The kept anchor carries the index's resolved path/lines,
// not the model's (possibly hallucinated) spelling.
export function groundAnchors(index, anchors) {
  const grounded = [];
  const dropped = [];
  for (const a of anchors || []) {
    // issue-286: a documentation line-range cite (`file@L<start>-<end>`)
    // grounds iff the file resolves to exactly one indexed file and the range
    // starts in bounds — the model cannot invent a doc path or a line range
    // (same anti-fabrication contract as function cites).
    const lm = a.func && a.func.match(/^L(\d+)(?:-(\d+))?$/);
    if (lm) {
      const start = Number(lm[1]);
      const end = lm[2] ? Number(lm[2]) : start;
      const hit = resolveIndexedFile(index, a.file);
      if (!hit || hit.ambiguous) {
        dropped.push({ ...a, reason: hit && hit.ambiguous ? 'cited doc path ambiguous in index' : 'cited doc file not in index' });
        continue;
      }
      const lines = index.fileLines.get(hit) || [];
      if (start < 1 || start > lines.length || end < start) {
        dropped.push({ ...a, reason: 'cited doc line range out of bounds' });
        continue;
      }
      grounded.push({ file: hit, func: '', start, end: Math.min(end, lines.length), element: a.element, kind: 'lines' });
      continue;
    }
    if (!a.func) { dropped.push({ ...a, reason: 'no function name to verify' }); continue; }
    const matches = index.findFunctionMatches(a.func, a.file || null);
    if (!matches || matches.length === 0) {
      dropped.push({ ...a, reason: 'cited function not found in index' });
      continue;
    }
    const m = matches[0];
    grounded.push({ file: m.filepath, func: m.name, start: m.start, end: m.end, element: a.element, ambiguous: matches.length > 1 });
  }
  return { grounded, dropped };
}

// Reusable CLAIM-CHART formatter (#284 --pseudo-claims-chart): render the claim
// AS WRITTEN — a preamble row plus one row per element/step of the claim prose
// (elements are semicolon-delimited; the drafter is instructed to write that
// way, so it works model-independently — Claude's coarse anchors or Gemini's
// fine ones alike). Each grounded anchor's cite is attached to the element whose
// text it most overlaps; elements with no confident cite are left blank
// (cite→element alignment is deliberately approximate for now). Kept
// standalone/exported so claim-search / claim-analyze can reuse the same
// element→evidence view rather than reinventing it.
export function formatClaimChart(prose, grounded) {
  const esc = (s) => String(s).replace(/\s+/g, ' ').replace(/\|/g, '\\|').trim();
  const cite = (a) => a.kind === 'lines'
    ? `\`${a.file}@L${a.start}-${a.end}\` (doc)`
    : `\`${a.file}@${a.func}\`${a.start ? ` (L${a.start}-${a.end})` : ''}`;
  const kw = (s) => new Set(String(s).toLowerCase().match(/[a-z][a-z0-9_]{3,}/g) || []);
  // Parse claim prose: preamble = text through the first ':'; elements = the
  // remainder split on ';' (standard method-claim form).
  const text = String(prose || '').trim();
  const ci = text.indexOf(':');
  const preamble = ci >= 0 ? text.slice(0, ci + 1).trim() : '';
  const body = ci >= 0 ? text.slice(ci + 1) : text;
  const elements = body.split(';').map((e) => e.trim().replace(/[.\s]+$/, '')).filter(Boolean);
  // Best-effort: attach each grounded cite to the element it most overlaps.
  const elemKw = elements.map(kw);
  const elemCites = elements.map(() => []);
  const unmatched = [];
  for (const a of grounded || []) {
    const aw = kw(a.element || '');
    let best = -1, score = 0;
    for (let i = 0; i < elemKw.length; i += 1) {
      let s = 0; for (const w of aw) if (elemKw[i].has(w)) s += 1;
      if (s > score) { score = s; best = i; }
    }
    const c = cite(a);
    if (best >= 0 && score >= 1) { if (!elemCites[best].includes(c)) elemCites[best].push(c); }
    else unmatched.push(c);
  }
  const lines = ['| # | Claim element / step | Cited code |', '|---|---|---|'];
  let n = 0;
  if (preamble) { n += 1; lines.push(`| ${n} | ${esc(preamble)} | _Preamble_ |`); }
  for (let i = 0; i < elements.length; i += 1) {
    n += 1;
    lines.push(`| ${n} | ${esc(elements[i])} | ${elemCites[i].join('<br>')} |`);
  }
  if (!preamble && !elements.length) lines.push('| — | _(no claim text to chart)_ | — |');
  if (unmatched.length) lines.push('', `_Grounded cite(s) not matched to a specific element: ${unmatched.join(', ')}._`);
  return lines;
}

/**
 * `--pseudo-claims --candidates <path>` (#284 B1): emit an UNRANKED mechanism
 * candidate anchors.lst via the deterministic grouper (mechanism-grouper.js),
 * instead of drafting. `--group-by concept` selects the token-only baseline;
 * `--file-seed` enables the opt-in residual file seed. `--ground-truth <gt.lst>`
 * scores the candidates' recall/precision against a hand-authored anchor set (a
 * dev path) instead of writing candidates. This is the front half of the pipeline
 * whose ranked one-command form is the future `--pseudo-claims --auto` (B2).
 */
export async function doEmitCandidates(index, args) {
  const indexName = String(args.index_path || '').replace(/[\\/]+$/, '').split(/[\\/]/).pop() || '?';
  let result;
  try {
    result = groupMechanisms(index, {
      indexName,
      mode: args.group_by === 'concept' ? 'concept' : 'multi',
      fileSeed: !!args.file_seed,
      useDocs: !!args.use_docs,
      catalogSeed: !!args.catalog_seed,
      literalSeed: !!args.literal_seed,
      bodyMatchSeed: !!args.body_match_seed,
    });
  } catch (e) {
    console.error(`--pseudo-claims --candidates: grouping failed: ${e.message}`);
    process.exitCode = 1;
    return;
  }

  // --ground-truth: score instead of emit (dev path).
  if (args.ground_truth) {
    let gtText;
    try { gtText = fs.readFileSync(args.ground_truth, 'utf8'); }
    catch (e) { console.error(`--ground-truth: cannot read '${args.ground_truth}': ${e.message}`); process.exitCode = 1; return; }
    const s = scoreGrouping(index, result, gtText);
    console.log(`# mechanism-grouper score  index=${indexName}  group-by=${result.mode}  candidates=${result.groups.length} groups`);
    console.log(`# ground-truth: ${s.gtGroups} groups, ${s.scored} scored  avgRecall=${s.avgRecall.toFixed(2)} avgPrecision=${s.avgPrecision.toFixed(2)}`);
    for (const r of s.rows) {
      if (r.note) { console.log(`   ${r.label}: ${r.note}`); continue; }
      console.log(`   ${r.recall.toFixed(2)}R ${r.precision.toFixed(2)}P  ${r.together}/${r.resolved} together, in a cluster of ${r.clusterSize}  — ${r.label.slice(0, 58)}`);
    }
    return;
  }

  const outPath = (args.candidates && args.candidates !== '-' && args.candidates !== '.') ? args.candidates : null;

  // --rank (#284 ranker Phase 0): score each candidate with a bounded LLM
  // exploration-PRIORITY verdict, then emit the candidates ANNOTATED and sorted
  // highest-priority first. Still observe-only — the ANCHORS are identical; only
  // the `# ` headers gain a [P..] tag and the group order reflects priority.
  // Nothing is dropped or merged (that is Phase 1 / --auto). The pcrun soak
  // measures these verdicts.
  if (args.rank) {
    const model = resolveModel(args);
    if (!model || model.kind === 'error') {
      console.error(`--rank needs a model: pass --llm <provider> or --model <gguf> (${model?.error || 'none configured'}).`);
      process.exitCode = 1; return;
    }
    let drafter;
    try { drafter = makeDrafter(model, 0.2); }
    catch (e) { console.error(`--rank: ${e.message}`); process.exitCode = 1; return; }
    // pseudo-claims-cost-guard: project the comparative-ranking spend from the
    // ACTUAL batch prompts (cheap string builds), +30% for the playoff rounds
    // (the ffmpeg 244-group run's two playoff rounds added ~30%). Gate before
    // the first API call; --force / CE_CLAIMS_COST_GUARD override.
    {
      const calls = [];
      for (let i = 0; i < result.groups.length; i += 20) {
        const batch = result.groups.slice(i, i + 20);
        const { sys, user } = buildBatchPrompt(batch, index, {});
        calls.push({ inChars: (sys.length + user.length) * 1.3, outTokens: Math.min(2000, 120 + batch.length * 60) * 1.3 });
      }
      if (!claimsCostGate(model, calls, `rank ${result.groups.length} candidates, ${Math.ceil(result.groups.length / 20)} batches + playoff`, args)) return;
    }
    resetCloudUsage();
    const mlabel = model.label || model.model || 'model';
    console.error(`# mechanism-ranker: scoring ${result.groups.length} candidates via ${mlabel}…`);
    const scored = await rankCandidates(result.groups, index, drafter, {});
    const rankCost = actualCostLine(model);
    if (rankCost) console.error(rankCost);
    const vByLabel = new Map(scored.map((s) => [s.label, s.verdict]));
    const sorted = [...result.groups].sort((a, b) => ((vByLabel.get(b.label)?.priority ?? -1) - (vByLabel.get(a.label)?.priority ?? -1)));
    const ranked = scored.filter((s) => s.verdict).length;
    const caveat = [
      '# ILLUSTRATIVE claim-candidate ranking — a FAST, SURFACE heuristic to suggest where to',
      '# look FIRST, NOT legal analysis and NOT a judgment of novelty, importance, or worth.',
      '# A low P-score means only that a cluster RESEMBLES a common pattern or borrowed code at a',
      "# glance — NOT that it lacks value or novelty. Routine-looking code can be the crux, and",
      "# the user's considered judgment governs. Verify independently; not an admission about",
      '# any code or claim.',
      '#',
    ];
    const lines = [...caveat, `# mechanism-ranker  index=${indexName}  group-by=${result.mode}  ${result.groups.length} groups — RANKED by ${mlabel} (observe-only; anchors unchanged; ${ranked}/${scored.length} scored) — first-pass exploration priority; tag is [P0-3 signal/fold — what it resembles]`];
    for (const g of sorted) {
      const v = vByLabel.get(g.label);
      const tag = v ? `  [P${v.priority} ${v.signal}/${v.fold}${v.note ? ' — ' + v.note : ''}]` : '  [unscored]';
      const purpose = harvestPurpose(index, g.label, g.members);
      lines.push('', `# ${g.label}  (${g.members.length} fns)${tag}${purpose ? '  — ' + purpose : ''}`);
      // issue-289-doc-anchor-enrichment: doc anchors first (budget-first placement).
      if (args.doc_anchors) for (const d of docAnchorsForGroup(index, g.label, g.members)) lines.push(d);
      for (const f of g.members) { const spec = f.name.includes('@') ? f.bare : f.name; lines.push(`${f.file}@${spec}`); }
    }
    const rankedText = lines.join('\n') + '\n';
    if (outPath) {
      fs.writeFileSync(outPath, rankedText, 'utf8');
      console.error(`# wrote ${result.groups.length} RANKED candidate group(s) to ${outPath}  (${indexName}, ${ranked}/${scored.length} scored by ${mlabel})`);
    } else {
      process.stdout.write(rankedText);
    }
    return;
  }

  const text = formatAnchors(result, {
    indexName,
    minComm: GROUPER_DEFAULTS.minComm,
    purposeFor: (label, members) => harvestPurpose(index, label, members),
    ...(args.doc_anchors ? { docAnchorsFor: (label, members) => docAnchorsForGroup(index, label, members) } : {}),
  });
  if (outPath) {
    fs.writeFileSync(outPath, text, 'utf8');
    console.error(`# wrote ${result.groups.length} candidate group(s) to ${outPath}  (${indexName}, group-by=${result.mode}, unranked; pre-filtered ${result.noiseFiles} noise files / ${result.noiseFns} fns)`);
  } else {
    process.stdout.write(text);
  }
}

/**
 * Handle `--pseudo-claims <anchors>`. Partitions anchors into groups (one
 * pseudo-claim each), resolves + extracts each, assembles a bounded evidence
 * pack per group, then either prints the packs (--dry-run / no model) or drafts
 * one grounded pseudo-claim per pack. Sets process.exitCode on error.
 */
export async function doPseudoClaims(index, args) {
  if (args.candidates || args.ground_truth || args.rank) { await doEmitCandidates(index, args); return; }
  const spec = args.pseudo_claims;

  let groups;
  try {
    groups = collectAnchorGroups(spec);
  } catch (e) {
    console.error(`--pseudo-claims: could not read anchor list '${String(spec).slice(1)}': ${e.message}`);
    process.exitCode = 1;
    return;
  }
  if (groups.length === 0) {
    console.error('--pseudo-claims: no anchors given. Provide "file@func;file@func" or @anchors.lst (one file@func per line; "# Label" lines separate claims).');
    process.exitCode = 1;
    return;
  }

  if (Number.isNaN(parseMinRank(args.min_rank))) {
    console.error(`--min-rank: expected 0-3 or P0-P3 (got '${args.min_rank}').`);
    process.exitCode = 1;
    return;
  }
  const totalGroups = groups.length;
  const mr = filterGroupsByMinRank(groups, args.min_rank);
  groups = mr.groups;
  if (mr.dropped) {
    console.error(`# --min-rank P${mr.floor}: drafting ${groups.length} of ${totalGroups} candidate group(s); ${mr.dropped} below the floor skipped.`);
    console.error('Tip: --min-rank 0 drafts every group; --min-rank 3 only the top tier.');
  }
  if (groups.length === 0) {
    console.error(`--pseudo-claims: no groups at or above --min-rank P${mr.floor}; nothing to draft (Tip: lower --min-rank).`);
    process.exitCode = 1;
    return;
  }
  // Selection disclosure for the artifact intro — a chart should say what it excluded.
  const selNote = mr.dropped ? ` ${groups.length} of ${totalGroups} candidate group(s) drafted (--min-rank P${mr.floor}).` : '';

  const multi = groups.length > 1;

  // Resolve + pack each group.
  const sections = [];
  let totalResolved = 0;
  let totalProblems = 0;
  groups.forEach((g, gi) => {
    const { resolved, problems } = resolveGroup(index, g);
    const { pack, truncatedAnchors, droppedForBudget } = buildPack(resolved);
    sections.push({ label: g.label, purpose: g.purpose || '', fold: g.fold || null, priority: g.priority ?? null, groupNum: gi + 1, resolved, problems, pack, truncatedAnchors, droppedForBudget });
    totalResolved += resolved.length;
    totalProblems += problems.length;
  });

  // Report dropped anchors to stderr (grouped when there are multiple claims),
  // so stdout stays a clean artifact.
  if (totalProblems) {
    console.error(`\n${totalProblems} anchor(s) dropped (did not resolve to a real function):`);
    for (const s of sections) {
      if (!s.problems.length) continue;
      if (multi) console.error(`  [${s.label || `group ${s.groupNum}`}]`);
      for (const p of s.problems) console.error(`  ✗ ${p.spec} — ${p.reason}`);
    }
    console.error('');
  }
  if (totalResolved === 0) {
    console.error('--pseudo-claims: no anchors resolved to real functions; nothing to draft.');
    process.exitCode = 1;
    return;
  }

  const withAnchors = sections.filter((s) => s.resolved.length);
  const model = resolveModel(args);
  if (model && model.kind === 'error') {
    console.error(`--pseudo-claims: ${model.error}`);
    process.exitCode = 1;
    return;
  }
  const dryRun = !!args.dry_run || !model;
  // Evidence pack in the OUTPUT artifact: absent by default (keeps --pseudo-claims
  // lean); shown on --dry-run (the pack IS that mode's deliverable) or with
  // --include-evidence-pack. The model ALWAYS receives the pack as INPUT
  // (buildPack -> drafter, below) — this flag only controls the artifact.
  const showPack = dryRun || !!args.include_evidence_pack;
  const chartMode = !dryRun && !!args.pseudo_claims_chart;
  const temperature = args.temperature ?? 0;
  const modelDesc = !model ? '' : model.kind === 'gguf' ? `local GGUF ${model.modelPath}` : `${model.label} (${model.model})`;

  // If drafting, build the drafter up front (the air-gap gate + key check may
  // throw here).
  let drafter = null;
  if (!dryRun) {
    try {
      drafter = makeDrafter(model, temperature);
    } catch (e) {
      console.error(`--pseudo-claims: ${e.message}`);
      process.exitCode = 1;
      return;
    }
    // pseudo-claims-cost-guard: packs are already built (s.pack), so the
    // drafting projection is exact — pack + system prompt in, 900 out per
    // claim. Gate before the first API call.
    const calls = withAnchors.map((s) => ({
      inChars: PSEUDO_CLAIM_GENERATE_SYS.length + 200 + (s.pack ? s.pack.length : 0),
      outTokens: 900,
    }));
    if (!claimsCostGate(model, calls, `${withAnchors.length} drafts`, args)) return;
    resetCloudUsage();
    process.stderr.write(`Drafting ${withAnchors.length} pseudo-claim(s) via ${modelDesc}…\n`);
  }

  // Draft each group's claim (sequentially; a shared GGUF session is not
  // concurrent-safe, and endpoints are gentler one at a time).
  const drafts = [];
  if (!dryRun) {
    for (let i = 0; i < withAnchors.length; i++) {
      const s = withAnchors[i];
      try {
        // Label + purpose as ONE line (separating them weakened both — the
        // ranker-purpose-signal lesson); triage annotations already stripped.
        const mech = s.label ? `${s.label}${s.purpose ? ' — ' + s.purpose : ''}` : '';
        const intent = mech ? `MECHANISM: ${mech}\n\n` : '';
        const raw = await drafter(PSEUDO_CLAIM_GENERATE_SYS, `${intent}CODE:\n${s.pack}`, 900);
        const { prose, anchors } = parseGeneratedClaim(raw);
        const { grounded, dropped } = groundAnchors(index, anchors);
        drafts.push({ prose, grounded, dropped });
        process.stderr.write(`  claim ${i + 1}/${withAnchors.length}: ${grounded.length} grounded anchor(s)${dropped.length ? `, ${dropped.length} ungrounded dropped` : ''}\n`);
      } catch (e) {
        drafts.push({ error: e.message });
        process.stderr.write(`  claim ${i + 1}/${withAnchors.length}: draft failed — ${e.message}\n`);
      }
    }
    const draftCost = actualCostLine(model);
    if (draftCost) process.stderr.write(draftCost + '\n');
  }

  // Build the artifact: Block A once, then one section per non-empty group.
  const out = [];
  out.push(PSEUDO_CLAIM_CAVEAT_A);
  out.push('');
  if (dryRun) {
    out.push(`_Deterministic scaffold (dry run): below is the exact, size-capped evidence pack a model would be handed — one per pseudo-claim (${withAnchors.length}).${selNote} To draft, pass \`--model <gguf>\` or set \`CE_OPENAI_API_URL\` (drop \`--dry-run\`)._`);
  } else {
    out.push(`_Drafted from ${withAnchors.length} evidence pack(s) via ${modelDesc}.${selNote} Each claim's cited anchors are **grounded** — verified to resolve to a real function in the index; ungrounded citations are dropped.${showPack ? ' The evidence pack the draft was grounded in follows each claim.' : ' Pass --include-evidence-pack to append each claim\'s evidence pack.'}_`);
  }
  out.push('');

  // chart-toc-rank-display: a multi-claim chart opens with a rank-and-name
  // contents table (drafted preambles as names; labels alone in dry-run).
  if (withAnchors.length >= 2) {
    const rows = withAnchors.map((s, i) => ({
      n: i + 1,
      label: s.label,
      priority: s.priority,
      preamble: !dryRun && drafts[i] && drafts[i].prose ? claimPreambleSnippet(drafts[i].prose) : '',
    }));
    for (const ln of formatChartToc(rows)) out.push(ln);
  }

  withAnchors.forEach((s, i) => {
    const label = s.label ? ` — ${s.label}` : '';
    const rankSuffix = s.priority != null ? `  (P${s.priority})` : '';
    out.push(`## Pseudo-claim ${i + 1}${label}${rankSuffix}`);
    out.push('');
    // #291 Part C: a split-flagged group is over-broad by the ranker's own
    // verdict — disclose that this claim may cover only a slice of it.
    if (s.fold === 'split') {
      out.push('_The ranker marked this group `split` (over-broad); this claim may cover only a slice of it._');
      out.push('');
    }

    if (!dryRun) {
      const d = drafts[i];
      out.push(PSEUDO_CLAIM_CAVEAT_B);
      out.push('');
      if (d.error) {
        out.push(`_Draft failed: ${d.error}. The evidence pack is below for reference._`);
        out.push('');
      } else {
        out.push(d.prose || '_(model produced no claim text)_');
        out.push('');
        if (chartMode) {
          out.push(`### Claim chart (${d.grounded.length} grounded cite${d.grounded.length === 1 ? '' : 's'}${d.dropped.length ? `, ${d.dropped.length} ungrounded dropped` : ''})`);
          out.push('');
          for (const ln of formatClaimChart(d.prose, d.grounded)) out.push(ln);
        } else {
          out.push(`### Cited anchors (${d.grounded.length} grounded${d.dropped.length ? `, ${d.dropped.length} ungrounded dropped` : ''})`);
          out.push('');
          for (const a of d.grounded) {
            out.push(a.kind === 'lines'
              ? `- \`${a.file}@L${a.start}-${a.end}\` — documentation excerpt${a.element ? ` — ${a.element}` : ''}`
              : `- \`${a.file}@${a.func}\` — L${a.start}-${a.end}${a.element ? ` — ${a.element}` : ''}`);
          }
          if (!d.grounded.length) out.push('- _(no cited anchor resolved to a real function)_');
        }
        if (d.dropped.length) {
          out.push('');
          out.push(`_Dropped (cited but not found in index): ${d.dropped.map((a) => `\`${a.file}@${a.func || '?'}\``).join(', ')}._`);
        }
        out.push('');
      }
      if (!showPack) {
        const disc = packDisclosure(s);
        if (disc) { out.push(disc); out.push(''); }
      }
      if (showPack) out.push('### Evidence pack (the code this draft was grounded in)');
    } else {
      out.push(`### Anchors (${s.resolved.length})`);
      out.push('');
      for (const a of s.resolved) {
        out.push(a.kind === 'lines'
          ? `- \`${a.filepath}@L${a.start}-${a.end}\` — documentation excerpt (${a.end - a.start + 1} lines)`
          : `- \`${a.filepath}@${a.name}\` — L${a.start}-${a.end} (${a.end - a.start + 1} lines)`);
      }
      if (showPack) out.push('', '### Evidence pack');
    }

    if (showPack) {
      out.push('');
      if (s.truncatedAnchors.length) {
        out.push(`_Truncated to the ${PACK_PER_ANCHOR_CHARS}-char per-anchor cap: ${s.truncatedAnchors.map((x) => `\`${x}\``).join(', ')}._`);
        out.push('');
      }
      if (s.droppedForBudget) {
        out.push(`_${s.droppedForBudget} anchor(s) omitted after the ${PACK_TOTAL_CHARS}-char per-claim pack budget was reached._`);
        out.push('');
      }
      out.push(s.pack);
      out.push('');
    }
  });
  out.push(PSEUDO_CLAIM_CAVEAT_C);

  const text = out.join('\n') + '\n';

  // Emit to stdout or --pseudo-out <file>.
  if (args.pseudo_out) {
    try {
      fs.writeFileSync(args.pseudo_out, text, 'utf8');
      console.log(`Wrote pseudo-claims artifact to ${args.pseudo_out} — ${withAnchors.length} pseudo-claim(s), ${totalResolved} anchor(s)${totalProblems ? `, ${totalProblems} dropped` : ''}${dryRun ? ' (dry run — no model draft)' : ''}.`);
    } catch (e) {
      console.error(`--pseudo-claims: could not write '${args.pseudo_out}': ${e.message}`);
      process.exitCode = 1;
    }
  } else {
    process.stdout.write(text);
  }
}
